### ISSUE TITLE
path 'logsearch-for-cloudfoundry-boshrelease' does not exist in the given tree (Rugged::TreeError)

### ISSUE THREAD

**Issue by ramelito** [cloudfoundry-community/logsearch-boshworkspace#19]
ubuntu@bastion:~/workspace/deployments/logsearch-boshworkspace$ bosh prepare deployment

Fetching release 'logsearch' to satisfy template references
Version '19' has been checkout into:
- /home/ubuntu/workspace/deployments/logsearch-boshworkspace/.releases/logsearch
  Fetching release 'logsearch-for-cloudfoundry' to satisfy template references
  /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/workspace/release.rb:86:in `path': the path 'logsearch-for-cloudfoundry-boshrelease' does not exist in the given tree (Rugged::TreeError)
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/workspace/release.rb:86:in`releases_tree'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/workspace/release.rb:94:in `final_releases'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/workspace/release.rb:120:in`release'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/workspace/release.rb:16:in `update_repo'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/cli/commands/prepare.rb:32:in`block in prepare_release_repos'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/cli/commands/prepare.rb:28:in `each'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/cli/commands/prepare.rb:28:in`prepare_release_repos'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh-workspace-0.9.1/lib/bosh/cli/commands/prepare.rb:18:in `prepare'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh_cli-1.3098.0/lib/cli/command_handler.rb:57:in`run'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh_cli-1.3098.0/lib/cli/runner.rb:56:in `run'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/gems/bosh_cli-1.3098.0/bin/bosh:19:in`<top (required)>'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/bin/bosh:23:in `load'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/bin/bosh:23:in`<main>'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
  from /home/ubuntu/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in`<main>'

**Comment by emirozer** [comment]
Having the same issue over here.. 

I have found this https://github.com/logsearch/logsearch-for-cloudfoundry/pull/78

Probably related, but i tried to init and update the submodule by hand, still not helping.. tried giving the absolute path.. still no use..

**Comment by emirozer** [comment]
@drnic @rkoster  any ideas ?

**Comment by drnic** [comment]
I think the boshrelease repo was moved to its own repo.

**Comment by rkoster** [comment]
just remove `path` line from the releases for the deployment you use.

**Comment by rkoster** [comment]
That should work I'm happy to merge a PR for it

**Comment by RaphaelAudet** [comment]
You also need to use version of the release after the move-out. 

The following worked

```
- name: logsearch-for-cloudfoundry
  version: latest
  ref: 50833a0
  git: https://github.com/logsearch/logsearch-for-cloudfoundry.git
```

after upgrading bosh-workspace gem to version 0.9.9
