### ISSUE TITLE
logsearch-filters-common/bin/install_deps.sh: No such file or directory

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/logsearch-boshworkspace#4]
```
$ rake filters:update

...

Adding community plugins ... (takes a few minutes)
./bin/install_deps.sh
./bin/install_deps.sh: line 4: /home/ubuntu/workspace/deployments/logsearch-boshworkspace/tmp/logsearch-filters-cf/vendor/logsearch-filters-common/bin/install_deps.sh: No such file or directory
rake aborted!
Command failed with status (127): [./bin/install_deps.sh...]
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:28:in `block (3 levels) in <top (required)>'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:38:in `block (3 levels) in in_filter_dirs'
/home/ubuntu/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:236:in `block in with_clean_env'
/home/ubuntu/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:223:in `with_original_env'
/home/ubuntu/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:229:in `with_clean_env'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:38:in `block (2 levels) in in_filter_dirs'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:37:in `chdir'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:37:in `block in in_filter_dirs'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:36:in `each'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:36:in `in_filter_dirs'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:28:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => filters:update => filters:install_deps
(See full trace by running task with --trace)
```

**Comment by drnic** [comment]
If I manually run install it seems to work:

```
cd tmp/logsearch-filters-common
./bin/install_deps.sh
...
Adding community plugins ... (takes a few minutes)
```

**Comment by drnic** [comment]
Can reproduce for logsearch-filters-cf:

```
$ ./bin/install_deps.sh 
./bin/install_deps.sh: line 4: /home/ubuntu/workspace/deployments/logsearch-boshworkspace/tmp/logsearch-filters-cf/vendor/logsearch-filters-common/bin/install_deps.sh: No such file or directory
```

**Comment by drnic** [comment]
Not even sure logsearch-filters-cf/bin/install_deps.sh does anything interesting.

**Comment by drnic** [comment]
Commenting out logsearch-filters-cf/bin/install_deps.sh leads to following error:

```
./bin/build-and-test.sh
===> Building ...
./bin/build-and-test.sh: line 8: ./vendor/logsearch-filters-common/bin/build.sh: No such file or directory
rake aborted!
Command failed with status (1): [./bin/build-and-test.sh...]
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:34:in `block (3 levels) in <top (required)>'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:40:in `block (3 levels) in in_filter_dirs'
/home/ubuntu/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:236:in `block in with_clean_env'
/home/ubuntu/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:223:in `with_original_env'
/home/ubuntu/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:229:in `with_clean_env'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:40:in `block (2 levels) in in_filter_dirs'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:39:in `chdir'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:39:in `block in in_filter_dirs'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:38:in `each'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:38:in `in_filter_dirs'
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:34:in `block (2 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by drnic** [comment]
Ok, so the issue was that `git submodule update --init` needed to be run after cloning filter repos.

Next I get:

```
./bin/build-and-test.sh
===> Building ...
===> Testing ...
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :elasticsearch=>true, :broken=>true}
.........F

Failures:

  1) LogStash::Filters::Grok Ensure non-NATS messages are ignored "{"@type":"relp","host":"1.2.3.4","@message":"<78>Ap..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected "2014-04-24T04:03:06.000Z", but got "2015-04-24T04:03:06.000Z"
     # ./test/logstash/snippets/vcap-spec.rb:72:in `(root)'
     # ./vendor/logstash/lib/logstash/runner.rb:154:in `run'

Finished in 6.21 seconds
10 examples, 1 failure

Failed examples:

rspec ./vendor/logstash/spec/test_utils.rb:94 # LogStash::Filters::Grok Ensure non-NATS messages are ignored "{"@type":"relp","host":"1.2.3.4","@message":"<78>Ap..." when processed
rake aborted!
Command failed with status (1): [./bin/build-and-test.sh...]
/home/ubuntu/workspace/deployments/logsearch-boshworkspace/Rakefile:33:in `block (3 levels) in <top (required)>'
```
